# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: Southeastern Triathlon Collegiate Conference
description: "USA Triathlon Conference for Collegiate Clubs in SC, GA, TN, MS, and AL"
keywords: "triathlon, southeast, college, USAT"

# Site settings
url: http://sectc.org
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : Alex Pawlowski
  job       : Webmaster
  bio       : "Webmaster for SECTC"
  thumb     : /images/author.jpg
  email     : #
  url       : https://sectc.github.io

repo: http://github.com/sectc/sectc.github.io

# comments
#disqus_shortname: "knoxdata"

gems:
  - github-pages
  - jekyll-sitemap
